[versions]
# plugins
kotlin = "2.2.0"
intelliJPlatform = "2.7.0"
changelog = "2.3.0"
qodana = "2025.1.1"
kover = "0.9.1"

# libraries
jsonSerialization = "1.9.0"
datetime = "0.6.2"
ktor = "3.3.0"

junit = "5.13.4"


[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }

[libraries]
junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }

jsonSerialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json-jvm", version.ref = "jsonSerialization" }
datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime-jvm", version.ref = "datetime" }

ktorCore = { group = "io.ktor", name = "ktor-client-core-jvm", version.ref = "ktor" }
ktorCio = { group = "io.ktor", name = "ktor-client-cio-jvm", version.ref = "ktor" }
ktorResources = { group = "io.ktor", name = "ktor-client-resources-jvm", version.ref = "ktor" }
ktorJsonSerialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json-jvm", version.ref = "ktor" }
ktorContentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation-jvm", version.ref = "ktor" }